before_script:
  - apt-get update -qy

cache:
  paths:
    - node_modules/

pages:
  image: ruby:2.4.0
  stage: deploy
  script:
    - curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
    - bash nodesource_setup.sh
    - apt-get install -y nodejs build-essential
    - npm install
    - gem install bundler
    - bundle install
    - bundle exec middleman build --build-dir=public
  artifacts:
    paths:
      - public
      - node_modules/
  only:
    - master

